version: "3"
services:
  testbed_solr:
    image: "dtobtn/testbed_solr:latest"
    ports:
      - "8983:8983"
    restart: always
    container_name: testbed_solr
    volumes:
      - searchdata:/var/solr/server/solr
#  testbed_indexer:
#    image: "ryanhyma/testbed_indexer:1.0.0"
#    build:
#      context: ../testbed-indexer/
#      dockerfile: Dockerfile
#    ports:
#      - "8001:8001"
#    restart: always
#    container_name: testbed_indexer
#    depends_on: 
#      - testbed_solr
#    volumes:
#      - indexdata:/opt/indexer-data
  #testbed_rest:
  #  image: "ryanhyma/testbed_rest:1.0.0"
  #  build:
  #    context: ../testbed-rest/
  #    dockerfile: Dockerfile
  #  ports:
  #    - "9191:9191"
  #  restart: always
  #  container_name: testbed_rest
  #  depends_on: 
  #    - testbed_solr
  testbed_web:
    image: "dtobtn/testbed_web:latest"
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    restart: always
    container_name: testbed_web
    depends_on: 
      - testbed_solr
volumes:
 searchdata:
 indexdata:
        