apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: testbed-web
  name: testbed-web
  namespace: testbed
  selfLink: /api/v1/namespaces/testbed/services/testbed-web
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: testbed-web
    app.kubernetes.io/name: web
  sessionAffinity: None
  type: ClusterIP
