name: Deploy to AKS Cluster
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn install --file parent/pom.xml
    - name: Build with Maven
      run: mvn install --file pom.xml
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - run: |
        docker build -f ./docker/Dockerfile . -t dtobtn/testbed-web:${{ github.sha }}
        docker push dtobtn/testbed-web:${{ github.sha }}
      
    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: tbs-prod-aks
        resource-group: tbs-prod-rg
        
    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          kubernetes/testbed-web-deployment.yml
          kubernetes/testbed-web-service.yml
        images: |
          dtobtn/testbed-web:${{ github.sha }}
        namespace: |
          testbed
